"""Четыре таблицы сервиса определения орбит

Revision ID: 8ad9a9fb2b40
Revises:
Create Date: 2026-08-17 13:15:02.347530

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8ad9a9fb2b40"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "od_identifications",
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column(
            "candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("confirmed_norad_id", sa.Integer(), nullable=True),
        sa.Column("confirmed_by_sub", sa.String(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_od_identifications")),
    )
    op.create_table(
        "od_sessions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=True),
        sa.Column("owner_sub", sa.String(), nullable=False),
        sa.Column("seed_tle0", sa.String(), nullable=False),
        sa.Column("seed_tle1", sa.String(), nullable=False),
        sa.Column("seed_tle2", sa.String(), nullable=False),
        sa.Column("seed_source", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_od_sessions")),
    )
    op.create_table(
        "od_fit_runs",
        sa.Column("session_uuid", sa.Uuid(), nullable=False),
        sa.Column("author_sub", sa.String(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "elements_in", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "elements_out", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("tle0", sa.String(), nullable=False),
        sa.Column("tle1", sa.String(), nullable=False),
        sa.Column("tle2", sa.String(), nullable=False),
        sa.Column("epoch_mjd", sa.Float(), nullable=False),
        sa.Column("rms_khz", sa.Float(), nullable=False),
        sa.Column("rms_pre_khz", sa.Float(), nullable=False),
        sa.Column("n_points", sa.Integer(), nullable=False),
        sa.Column(
            "per_observation", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("residuals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "prior_dominated", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("published_mode", sa.String(), nullable=True),
        sa.Column("published_tle_id", sa.Integer(), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_uuid"],
            ["od_sessions.uuid"],
            name=op.f("fk_od_fit_runs_session_uuid_od_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_od_fit_runs")),
    )
    op.create_table(
        "od_session_observations",
        sa.Column("session_uuid", sa.Uuid(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "calibration", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("extraction_status", sa.String(), nullable=False),
        sa.Column("extraction_error", sa.String(), nullable=True),
        sa.Column(
            "diagnostics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("points", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_uuid"],
            ["od_sessions.uuid"],
            name=op.f("fk_od_session_observations_session_uuid_od_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("pk_od_session_observations")),
        sa.UniqueConstraint(
            "session_uuid",
            "observation_id",
            name=op.f("uq_od_session_observations_session_uuid_observation_id"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("od_session_observations")
    op.drop_table("od_fit_runs")
    op.drop_table("od_sessions")
    op.drop_table("od_identifications")
    # ### end Alembic commands ###
